### ISSUE TITLE
Inject does not update config property for sencha touch 2.0

### ISSUE THREAD

**Issue by jachenry** [deftjs/DeftJS#1]
My component hierarchy is App.ListMap <- App.Map <- Ext.Map.  Injecting the geo attribute creates a new local property (this.geo) but does not update the config property (this.getGeo()) defined in Ext.Map.  Calling this.getGeo() inside ListMap should return the injected value.

``` javascript
Ext.define('App.ListMap',  {
  extend: 'App.Map',
  mixins: [ 'Deft.mixin.Injectable' ],

  inject: {
    geo: 'geolocation'
  },

  ...
}

```

``` javascript
Deft.Injector.configure({
  geolocation: {
    className: 'Ext.util.Geolocation',
    parameters: [{
      autoUpdate: false,
      allowHighAccuracy: true
    }]
  },
});
```

**Comment by johnyanarella** [comment]
Thanks for reporting this issue.

Your example code looks exactly right.  Reviewing Ext.Map's declaration of geo, this should indeed be supported behavior.

This should be pretty easy to replicate - we'll look into it.
