### ISSUE TITLE
Create custom JSDuck theme.

### ISSUE THREAD

**Issue by johnyanarella** [deftjs/DeftJS#108]
Create a custom JSDuck theme:
- use the Deft JS `favicon.ico` instead of the standard Sencha icon added by JSDuck
- use the Deft JS Logo instead of the standard Sencha logo added by JSDuck
- tweak the colors via CSS to match the Deft JS color scheme
- replace the Sencha green colored loading animation
- integrate the version number into the title (also fix title - "Deft JS" instead of "DeftJS")
- switch to using a JSON config file instead of command-line arguments
- integrate the logic for applying the theme into the `build.xml` ant script

**Comment by johnyanarella** [comment]
The new theme can also now be seen in action here:

http://docs.deftjs.org/deft-js/0.9.0-pre/

**Comment by superstructor** [comment]
Looks good!
