### ISSUE TITLE
Append subclass injections

### ISSUE THREAD

**Issue by brian428** [deftjs/DeftJS#12]
It would be be nice if DeftJS allowed me to append injections to those declared in a superclass.

For example, say I have a BaseViewController that declares:

inject: [ 'someObject' ]

I then extend that in MyConcreteViewController and declare:

inject: [ 'someOtherObject' ]

The problem seems to be that the list of injections overwrites the superclass instead of appending to it. I was assuming it would work like the other configuration properties appear to, where I can declare config: values and rather than overwrite, they add onto those declared in a superclass.

So, while it's not a huge issue to declare inject: [ 'someObject', 'someOtherObject' ] in the child class, it does reduce the advantages of inheritance a bit.

**Comment by brian428** [comment]
Just to add, when it comes to the merging of the injections, I'd say if there is a conflict, subclass trumps superclass. That would seem to make the most sense and offer the most flexibility.

**Comment by johnyanarella** [comment]
Scheduled for inclusion in v0.6.6.

**Comment by johnyanarella** [comment]
Deferring to v0.6.7 in order to get a few fixes to high priority issues as v0.6.6.

**Comment by cnstaging** [comment]
+1

**Comment by johnyanarella** [comment]
The previously referenced commit broke `this.callParent()` functionality for classes that use both the `inject` and `controller` class annotation.  This is caused by the lack of Sencha class system book-keeping metadata on manually added interceptor functions (ex. $previous, $owner).

**Comment by johnyanarella** [comment]
Refactored the `inject` and `controller` class preprocessors to leverage `Ext.Base::override()` to intercept and override class constructors.

Added additional facade methods to `Deft.Class` to smooth out differences between Ext JS 4.0 and Ext JS 4.1 / Sencha Touch 2.0's APIs.
