### ISSUE TITLE
Downloadable version on deftjs.org is incorrect

### ISSUE THREAD

**Issue by joshnesbitt** [deftjs/DeftJS#13]
Hi,

The version you link to download on the deftjs.org site is very out of date. It references 0.1.1. It took me about half an hour to figure out why Deft.mvc.ViewController was failing to load, until I realised the download was incorrect.

Cheers,
Josh

**Comment by johnyanarella** [comment]
Thank you very much for pointing this out, Josh. Oops, I hope we didn't confuse and lose too many people with that old link.

**Comment by joshnesbitt** [comment]
You might also want to rebuild the pages when you change the readme, as that seems a bit off too :)

**Comment by johnyanarella** [comment]
Thanks.  Looks like the last couple modifications to the version history were not mirrored to there.  Fixed.
