### ISSUE TITLE
deft.js and deft-debug.js are not in the repo

### ISSUE THREAD

**Issue by apmanomark** [deftjs/DeftJS#133]
deft.js and deft-debug.js are not in the repo for v10.

The two files mentioned in the installation process are missing from the Deft repo.

https://github.com/deftjs/DeftJS/wiki/Adding-Deft-JS-to-Your-Application

The zip link in this page also does not work.

**Comment by brian428** [comment]
Thanks, updated the download link. It's also available at deftjs.org.
