### ISSUE TITLE
Errors do not propagate on class creation

### ISSUE THREAD

**Issue by joshnesbitt** [deftjs/DeftJS#14]
Hi,

When a class is created through the `Deft.mixin.Controllable` mixin, if the class creation fails a [generic error is thrown](https://github.com/deftjs/DeftJS/blob/master/src/js/Deft/mixin/Controllable.js#L36). Would this not be more useful to provide information related to why the class creation failed?

For example if you configure a store but the proxy fails to create, it's difficult to debug the exact point of failure. I'm happy to provide a pul request to fix this issue, I just need to know whether this is a valid request.

Cheers,
Josh

**Comment by johnyanarella** [comment]
Very valid.  I got burned by this myself last week.

**Comment by joshnesbitt** [comment]
I'll be submitting a pull request shortly.

**Comment by joshnesbitt** [comment]
I think the preference on this should be to log the message that is currently being thrown, then re-throw the error again. Would you agree?

**Comment by johnyanarella** [comment]
Agreed.

**Comment by johnyanarella** [comment]
Scheduled for inclusion in v0.6.6.
