### ISSUE TITLE
Controllable mixin should automatically Ext.require() referenced View Controller classes

### ISSUE THREAD

**Issue by johnyanarella** [deftjs/DeftJS#17]
Simplify developer effort for using the Controllable mixin by automatically `Ext.require()`-ing the referenced view controller class, rather than forcing the developer to specify the view controller class again in the `requires` class annotation.

**Comment by johnyanarella** [comment]
Scheduled for inclusion in v0.6.6.

**Comment by superstructor** [comment]
+1
