### ISSUE TITLE
Controllable mixin should add a 'getController()' method?

### ISSUE THREAD

**Issue by johnyanarella** [deftjs/DeftJS#18]
We've been considering enhancing the Controllable mixin to add a `getController()` accessor to the view that would provide access to the corresponding view controller.  Using this a view would be able to access its view controller to obtain references to any objects that were injected there and allowing both view and view controller to interact with the same injected prototype instance. Currently the controller has to access the store via whatever component it might have been assigned to (not ideal).

Thoughts?

**Comment by pjain11** [comment]
This will help with me with writing test for dynamically built view. With this feature I can get access to injected store in the view controller and wait for it to get loaded before running my tests.
