### ISSUE TITLE
Promise does not behave as it should?

### ISSUE THREAD

**Issue by ilann** [deftjs/DeftJS#20]
I would expect to see a log "THIS SHOULD BE SHOWN" as a correct behavior. the promise object should be resolved.
the code will only work if the resolve will occur after the promise.then.  

``` javascript

var defr = new Deft.promise.Deferred();
        var promise = defr.getPromise();


        defr.resolve();          

        promise.then(function(){

            console.log("THIS SHOULD BE SHOWN");

        }); 

```

**Comment by johnyanarella** [comment]
Interesting find.

Works as expected when you resolve with a value.

```
var defr = new Deft.promise.Deferred();
var promise = defr.getPromise();

defr.resolve('test'); // or even defr.resolve(null);

promise.then(function(){
    console.log("THIS SHOULD BE SHOWN");
});
```

We've been thinking about Promises strictly as future values, rather than signals, so the path where you are resolving without a value (i.e. with undefined) is not covered in unit tests.  We should fix that.

**Comment by johnyanarella** [comment]
Note to self: the check for `undefined` in `Deft.promise.Deferred::register()` is only applicable for the progress handler and should not prohibit immediate notification of `undefined` values for resolved, rejected or cancelled promises.

**Comment by ilann** [comment]
Cool. thanks
