### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by kristianmandrup** [deftjs/DeftJS#25]
Looks like a promising framework, but the README contains no instructions for best-practice on how to integrate it with either Sencha Touch 2 or ExtJS 4. Please provide an install/usage section with detailed instructions. 
my HEAD looks like this (using Phonegap):
Somehow Sencha Touch is autoloaded (using the microloader?), so DeftJS should be loaded only after the Ext namespace has been defined. Please advice.

``` html

    <!-- resources -->
    <script type="text/javascript" src="resources/javascript/i18n.js">
    </script>
    <script type="text/javascript" src="resources/javascript/locale_da.js">
    </script>
    <!--
    <script type="text/javascript" src="lib/deftjs/build/deft-debug.js">
    </script>    
    -->
    <!-- phonegap -->
    <script id="cordova" type="text/javascript" src="cordova-1.8.0.js"></script>
    <!-- The line below must be kept intact for Sencha Command to build your application -->
    <script id="microloader" type="text/javascript" src="sdk/microloader/development.js"></script>        
    <script type="text/javascript">
        // document.addEventListener("deviceready", app.mainLaunch, false);
    </script>    
</head>
```

**Comment by johnyanarella** [comment]
I'm only vaguely familiar with the Sencha Touch micro loader, but based on a quick skim of Sencha's documentation:

   http://www.sencha.com/blog/behind-sencha-command-and-the-build-process/

> All of this information is contained inside a JSON-formatted configuration file named app.json. Two of the most important configuration items to be highlighted here are “js” and “css”.
> With the new application structure, JavaScript and CSS assets should never be physically linked inside the HTML document (for example, manually added as &lt;script&gt;, &lt;style&gt; or &lt;link&gt; tags). Instead, they should be specified and maintained inside app.json as array of JavaScript and CSS items in the right execution order for the “js” and “css” keys, respectively.

I'd suggest something along these lines:

``` javascript
"js": [
    {
        "path": "sdk/sencha-touch.js"
    },
    {
        "path": "deft/deft.js" // or deft-debug.js
    },
    {
        "path": "app.js"
    }
]
```

Thanks for the suggestion, I'll keep this issue open as a reminder to include a Usage section in future documentation.  We are in the process of moving to Sencha style documentation (using their JSDuck tool) and the README will be revised at that point.

**Comment by kristianmandrup** [comment]
Cool :) Thanks!

**Comment by brian428** [comment]
Just closing this old, resolved issue.
