### ISSUE TITLE
A user defined constructor on a View will break the Deft.mixin.Controllable

### ISSUE THREAD

**Issue by cnstaging** [deftjs/DeftJS#27]
A user defined constructor on a View will break the Deft.mixin.Controllable from being able to hook into the object construction.

See the most basic constructor added on Lines 24-28 of the Controllable.js Spec
https://gist.github.com/3033957

Chances are this is breaking because of the "Ext.Function.createSequence" chain it's creating, but then being overridden the user defined constructor.

Question? Is there a way to hook or force call this when a view has a constructor?

One possible solution is to provide/expose a method similar to how Ext.util.Observable does. This would give us the best of both worlds, the current (automated) method for %80 of the time, and a manual way for those %20 edge cases.

Reference:
http://docs.sencha.com/ext-js/4-1/#!/api/Ext.util.Observable
"this.mixins.observable.constructor.call(this, config);"

**Comment by johnyanarella** [comment]
Thanks for reporting this.

I agree, it sounds like the user defined constructor is clobbering the interceptor function that was previously added to the instance to support the controller annotation.  I'll look into this immediately.

As of v0.6.6, we migrated the Controllable functionality out of the mix-in itself into a Secha Class system preprocessor.  At this point, the mix-in just serves as a marker.  (You discovered a bug in the logic used to detect that marker in issue #28.)

NOTE: I strongly suspect we'll be deprecating and removing the Controllable and Injectable mix-ins sometime before the release of v1.0.  In the future, you would simply use the `controller` and `inject` annotations without needing to include the corresponding mix-in anymore.

**Comment by johnyanarella** [comment]
After initial investigation, I see where I went wrong with the preprocessor implementation.  I plan to get a fix committed for this either later today or tomorrow.

**Comment by johnyanarella** [comment]
I believe I have resolved this issue locally for Ext JS 4.1 and Sencha Touch 2.01.  I'm working on back porting the solution to work with Ext JS 4.0.7 as well.  Once I have it working there as well, I'll commit my changes for your review.

**Comment by johnyanarella** [comment]
The proposed resolution for this issue has been committed.  It will be included in the next minor release, but is available now in prerelease form by checking out the `master` branch on GitHub.

Please let me know if this resolves your issue.  Thanks!

**Comment by cnstaging** [comment]
This worked great! Thank you.

I would love to see the use of just controller, rather than the mixin syntax. If you have a ticket for this feature I would like to discuss it further. We have Ext JS core extensions where we register our various preprocessors, We ran into issues with the ExtJS loader, due to it's private closure properties and not being able to define another hook. I wonder what  your approaches your considering.
