### ISSUE TITLE
Include support for both Ext JS 4 Class 'mixins:' syntax

### ISSUE THREAD

**Issue by cnstaging** [deftjs/DeftJS#28]
Ext JS 4.x syntax for mixins accepts either an array (of strings) or an object literal.

A minor issue that required us to change our existing code style on controllable views.

Reference: 
http://docs.sencha.com/ext-js/4-1/#!/api/Ext.Class-cfg-mixins

Current Syntax

``` javascript
mixins: [ 'Ext.util.Observable' ]
```

Does not work

``` javascript
mixins: {
    deftjs : 'Deft.mixin.Controllable',
    observable: 'Ext.util.Observable'
}
```

**Comment by johnyanarella** [comment]
Thanks for reporting this.

Our logic currently only checks for the Controllable mix-in's presence when `mixins` is specified as an Array. I'll update this to also include an appropriate check for when `mixins` is specified as an Object.

**Comment by johnyanarella** [comment]
The proposed resolution for this issue has been committed.  It will be included in the next minor release, but is available now in prerelease form by checking out the `master` branch on GitHub.

Please let me know if this resolves your issue.  Thanks!
