### ISSUE TITLE
Controlling a view that does not exists yet

### ISSUE THREAD

**Issue by catalinux** [deftjs/DeftJS#43]
Let's say that I have a Grid with record and a contextmenu that appera at rightclick on a row. Controlling the actions of the contextmenu 
from the Grid's ViewController would not work because will throw this error
`Uncaught Deft.mvc.ViewController.addComponentReference(): Error locating component: no component(s) found matching 'contextmenuusers menuitem[action=add]'`.

``` javascript
....
   control:{
...
     cmUsersEdit:{
            selector:'contextmenuusers menuitem[action=edit]',
            listeners:{
                click:function (menuitem) {
....
```

Which is the best way to do treat this type of situation.

**Comment by johnyanarella** [comment]
Question and associated discussion moved to Google Groups mailing list:

http://groups.google.com/group/deftjs/browse_thread/thread/9460215a8f7dd25c
