### ISSUE TITLE
Errors raised in promise callbacks should be logged to the console

### ISSUE THREAD

**Issue by rixo** [deftjs/DeftJS#59]
I understand that the Promise/A spec requires that exceptions raised in callback do not halt execution. However, silenting them completely leads to a lot of confusion, especially before one realizes that Deft is catching all their JS errors.

Errors can be logged to the console without crashing the execution thread. For example, in Chrome:

```
console.error(error.stack)
```

will give the same output as an uncatched error, with the "correct" stack trace. I don't know for other browsers, but even if the full stack cannot be provided, a notice should definitely be issued.

**Comment by brian428** [comment]
If a callback fails and the catch handler runs, the Deferred is rejected
and the failure handler is invoked. Still, you're probably right that it
could also send a message to the Deft Logger. Did you add an ER for this by
chance?

Thanks,

Brian

**Comment by rixo** [comment]
I am sorry, I don't know what an ER is. What does it mean?

**Comment by brian428** [comment]
Enhancement Request.

**Comment by rixo** [comment]
Like a Pull Request? I have just submitted one : https://github.com/deftjs/DeftJS/pull/60

Not sure that it will be useful to you though, I patched the JS but it seems that you develop Deft in CoffeeScript.
