### ISSUE TITLE
ComponentReference can't find Ext.grid.Panel plugin components

### ISSUE THREAD

**Issue by shmeltex** [deftjs/DeftJS#65]
When using `Ext.grid.Panel` plugin like `Ext.grid.plugin.RowEditing`, `addComponentReference()` can't find plugin's components.

For example:

``` coffeescript
Ext.define( 'TEST.view.ListView',
  extend: 'Ext.grid.Panel'
  controller: 'TEST.controller.ListController'

  initComponent: ->
    @plugins = [ Ext.create('Ext.grid.plugin.RowEditing') ]
    @columns = [
      {
        header: 'Column #1'
        dataIndex: 'columnOne'
        flex: 1
        editor:
          xtype: 'combo'
          itemId: 'myCombo'
      }
    ]
    @callParent(arguments)

Ext.define( 'TEST.controller.ListView',
  extend: 'Deft.mvc.ViewController'

  control:
    myCombo:
      selector: '#myCombo'
```

Generates error: `Deft.mvc.ViewController.addComponentReference(): Error locating component: no component(s) found matching '#myCombo'`

**Comment by brian428** [comment]
Row edit elements are floating components. This is why a component query starting with the grid panel cannot locate them. I believe you'd have to use a global component query to attempt to obtain a reference to floating components like the row edit elements. Deft might be able to attempt to fall back to a global selector if the initial search for a matching component returns nothing. I'm not sure we'd want to do this though, as the potential for selecting the wrong component becomes much higher with global selectors. So it will probably fall on the developer to decide when to write their own global selector in cases like this.

**Comment by brian428** [comment]
Actually I may have spoken too soon. It may not be the fact that they are floating but the fact that they are not created until after the controller is set up! Try setting up your control: block for the combobox to use a live selector and see if that gets it working: https://github.com/deftjs/DeftJS/wiki/ViewController-Live-Selectors

**Comment by shmeltex** [comment]
I tried:

``` coffeescript
Ext.define( 'TEST.controller.ListView',
  extend: 'Deft.mvc.ViewController'

  control:
    myCombo:
      live: true
      selector: '#myCombo'
      listeners:
        select: 'somethingSelected'
```

No errors, but will not catch events and getter returns null.

~~BTW, similar story is with `Ext.button.Split` - can't get to components defined as part of the `menu` option.~~ `Ext.button.Split` works without problems.

**Comment by brian428** [comment]
In that case it could still be the floating issue. To confirm, you can test by trying to grab a reference to these components manually in your VC, like @getView().down( "yourComponentQueryHere" ). If that works, then something may be up with the way Deft is looking up the component. If that doesn't work, then something has to be up with your selector, or the component you're trying to match is not a child item of the view this VC is managing.

**Comment by shmeltex** [comment]
`@getView().down('#myCombo')` returns `null`. 
`Ext.ComponentQuery.query('grid #myCombo')` also returns `null`. 
Only `Ext.ComponentQuery.query('#myCombo')` returns correct component.
Looks like in ExtJS plugins live in their own parallel universe

**Comment by brian428** [comment]
Yep, that's what I initially thought. These components don't live in a "parallel universe", but they also aren't added as children of the grid. They float over the other components, most likely attached to the document body itself. Their position appears to be managed via listeners on the grid (for scrolling, etc.). This is why the DeftJS selector can't locate it, because it doesn't sit in the child hierarchy of the grid panel. I'll add a note on this to the docs and the F.A.Q. Thanks.

**Comment by brian428** [comment]
Also, keep in mind that I _think_ you could add listeners on the grid itself for things like beforeedit, edit, or afteredit, which may let you gain access to the components you're looking for. Just an idea. If you'd like to continue the discussion, feel free to post to the mailing list (https://groups.google.com/forum/?fromgroups#!forum/deftjs), since this may interest other folks as well. Thanks.

**Comment by brian428** [comment]
Last follow up, in case it helps: if you add a listener on your grid for "beforeedit", the first argument passed to the handler is the RowEditing plugin itself. So if you named that argument "plugin", you could get at the MixedCollection of all of the editors for that row via: plugin.editor.items.

**Comment by shmeltex** [comment]
Thank you Brian! It was very helpful!
