### ISSUE TITLE
Consider adding DeftJS to TodoMVC

### ISSUE THREAD

**Issue by hdave** [deftjs/DeftJS#72]
I been looking into Javascript MVP/MVC pattern implementations as I have been dissatisfied with the default MVC capabilities within ExtJS.  I found a site call TodoMVC (http://todomvc.com/) which holds archetypal implementations of a simple TODO application using every major MV\* framework available to Javascript developers.

It just seems to me that your project should be advertised there so people like myself can really see the difference between out-of-the-box ExtJS and DeftJS.

**Comment by brian428** [comment]
This is a great idea and I had never heard of that site. I'll see what John thinks but it looks like it would be easy to build a DeftJS version of this simple ToDo app.

**Comment by brian428** [comment]
Done, but not sure if the TodoMVC folks will merge the pull request. If interested, for now the code can be found at https://github.com/brian428/todomvc/tree/__gh-pages_extjs-deftjs/labs/architecture-examples/extjs_deftjs

**Comment by brian428** [comment]
Made the list! http://todomvc.com/
