### ISSUE TITLE
Promises sensible behaviour for empty arrays

### ISSUE THREAD

**Issue by tomwidmer** [deftjs/DeftJS#74]
Promise.all([])
Promise.any([])
Promise.map([])
Promise.reduce([])

etc. don't currently do anything sensible. Some of them should resolve immediately to an empty array, while any, for example, should immediately do a reject and reduce should immediately resolve the initial value.

**Comment by johnyanarella** [comment]
Just to clarify, are you seeing this with v0.67, or with v0.8 (currently in the Master branch here on GitHub)?

**Comment by johnyanarella** [comment]
What you've described above sounds like the appropriate behavior, we'll investigate (and add some unit tests around those conditions in the process).

**Comment by tomwidmer** [comment]
I'm using master from around early December 2012 I think (so 0.8, but not current). The problem appears to be present in the current master as well.

**Comment by johnyanarella** [comment]
This behavior has now been resolved (and has unit test coverage) as part of the new Promises/A+ compliant rewrite of Deft JS's Promises.

See also: #82
