### ISSUE TITLE
Bug removing the beforedestroy listener in ViewController

### ISSUE THREAD

**Issue by asiragusa** [deftjs/DeftJS#75]
The following line ( https://github.com/deftjs/DeftJS/blob/master/src/coffee/Deft/mvc/ViewController.coffee#L230)

should be @getView().un( 'beforedestroy', @onViewBeforeDestroy, @ ) and not 

@getView().un( 'beforedestroy', @onBeforeDestroy, @ )

Please correct this typo ;)

**Comment by brian428** [comment]
Thanks, good catch.
