### ISSUE TITLE
Consider adding a JavaScript Code Coverage Tool

### ISSUE THREAD

**Issue by johnyanarella** [deftjs/DeftJS#79]
Consider adding a JavaScript code coverage tool to report unit test coverage.

For example:
- http://gotwarlost.github.com/istanbul/

**Comment by johnyanarella** [comment]
Tried using [blanket.js](http://blanketjs.org/).  Really clever library, and very easy to integrate.  Unfortunately, it assumes the target scripts included in an HTML test runner can be loaded twice (once un-instrumented, and a second time instrumented).  This doesn't align well with our needs due to initialization timing issues related to our Sencha Ext JS and Touch class preprocessors.  Loading deft-debug.js a second time causes the Deft JS inject: class preprocessor to process Deft.Injector::inject() as if it were a class annotation.  It also results in multiple copies of the class preprocessor to be registered - one un-instrumened, and the other instrumented.  Obviously, running the preprocessor logic twice causes problems.

Looking for a different solution.

**Comment by johnyanarella** [comment]
Added configuration files for running the Deft JS test suite via [Karma Test Runner](http://karma-runner.github.io/).

Looking into using Karma's coverage analysis features (which internally use [Istanbul](http://gotwarlost.github.com/istanbul/)).

**Comment by johnyanarella** [comment]
It's also important to note that because Deft JS has branches of code that are runtime and runtime version specific (i.e. Sencha Touch vs Ext JS, Ext JS 4.0.7 vs 4.1.0+), we won't ever get a report that tells us we have 100% coverage.  Analysis of coverage reports generated by any tool will need to take this into account.

**Comment by brian428** [comment]
Not an ideal solution, but if blanket is open source, could you hack it to ignore an inject() method? Just an idea...if that would make it work, I'd _think_ that would be a simple if block somewhere...

**Comment by brian428** [comment]
Doh...it's not blanket, it's Deft heh. And not sure we want to be tweaking Deft to ignore an inject function....

Hmm, actually, could that work? If they're using an inject property they can't also have an inject method, so testing if the value is named "inject" and is of type function might be an option?

**Comment by brian428** [comment]
Rambling on here....but maybe this would actually be a good thing? IF someone DID have a class with a method named inject(), we wouldn't want the Injector to see it as an injection target anyway. So making sure the value of inject isn't a function would also eliminate that possibility.

**Comment by johnyanarella** [comment]
True - the `inject` class preprocessor should probably check the data type when it encounters an `inject` property in a class definition to ensure it is a String, Object or Array.

**Comment by johnyanarella** [comment]
We could also check before registering the class preprocessor to see if it is already registered.

That said, in normal situations (outside of blanket's clever code coverage loading approach) this would be an error condition we'd probably want to alert the user to.

**Comment by johnyanarella** [comment]
It's handy that [Istanbul](http://gotwarlost.github.com/istanbul/) is already integrated with Karma.  One less third party integration we have to manage ourselves.  Karma (built by the Angular JS team) has a lot of momentum at the moment.

**Comment by superstructor** [comment]
Karma looks nice and appears to work with everything we need it to (Mocha / TravisCI / Sencha Cmd etc).

**Comment by johnyanarella** [comment]
Decision made: Karma (+ its integrated support for Istanbul).
