### ISSUE TITLE
Distribute as a Sencha Cmd Package

### ISSUE THREAD

**Issue by superstructor** [deftjs/DeftJS#85]
Sencha has added the ability to distribute packages via the sencha cmd tool.

See

http://docs.sencha.com/extjs/4.2.0/#!/guide/command_packages
http://docs.sencha.com/extjs/4.2.0/#!/guide/command_package_authoring

These can be made available via a remote repository e.g.:

`sencha repository add -address http://deftjs.org/packages -name deftjs`

And subsequently required in an `app.json` e.g.:

``` json
{
    "name": "MyApp",
    "requires": [
        "deftjs@1.0"
    ]
}
```

**Possible Benefits**
- Easy install of DeftJS for projects using Sencha Cmd
- Version dependencies with support for auto-upgrades e.g. "deftjs@1.0?" (? means latest available version that is backwards compatible with 1.0)
- DeftJS is automatically added to the class path during the application build `sencha app build`
- `sencha app build` includes only the DeftJS classes required by application classes, and everything including DeftJS ends up in a single JS file for distribution. More complex builds with seperate build files are also configurable with namespace or set based exclusions/inclusions.
- Public key based authorship

**Changes**
- Some minor changes to the project structure as part of copying into the result of `sencha generate package`
- Build script changes shouldn't be too bad as Sencha Cmd also uses Ant

What do you think of using this ?

If you like I can look into making the changes required for a pull request as I've already experimented with making a local package of DeftJS. You'd just need to replace the crypto key files regarding authorship etc.

Cheers

**Comment by brian428** [comment]
I think that's a fine idea. John?

**Comment by johnyanarella** [comment]
This sounds great to me!  We'd definitely appreciate help here.

**Comment by superstructor** [comment]
Ok great I'll get a pull request ready for this. Thanks.
