### ISSUE TITLE
Sencha Framework Picker Breaks Mocha's ?grep Filters

### ISSUE THREAD

**Issue by superstructor** [deftjs/DeftJS#88]
E.g. clicking a description header or running a single test (play icon) breaks.

This is due to the links not including the query parameters for the sencha framework picker so Ext is undefined.

Looking into a fix now.

**Comment by johnyanarella** [comment]
Good catch.  Let me know if there's anything I can do to help.

**Comment by superstructor** [comment]
This is unfortunately in test/lib/mocha-1.9.0/mocha.js

Lines [2317](https://github.com/deftjs/DeftJS/blob/master/test/lib/mocha-1.9.0/mocha.js#L2317) and [2348-2352](https://github.com/deftjs/DeftJS/blob/master/test/lib/mocha-1.9.0/mocha.js#L2348).

I could just fix this by changing e.g. `var url = '?grep=' + encodeURIComponent(suite.fullTitle());` to `var url = document.location.search + '&grep=' + encodeURIComponent(suite.fullTitle());`

However this would require maintaining changes to an upstream library.

A pull request to Mocha might be cleaner. A more general fix that could be merged upstream might be a bit more complex than the above example hack.

Replacing URLs in-place by a secondary script is not really an option because there will be some time while Mocha is running that the URLs are broken.

Thoughts ?

**Comment by johnyanarella** [comment]
Sounds like the querystring isn't viable for storing this particular state.  I guess that means we'll have to choose among other persistence mechanisms - i.e. cookies, local storage, etc.

That could make things trickier when we start trying to do automated testing.  We'll potentially need to continue to accept those querystring parameters and subsequently store that state via the chosen persistence mechanism.

**Comment by superstructor** [comment]
I like the solution of using localStorage, good idea.

Implemented, manually tested and pull request done.

**Comment by johnyanarella** [comment]
Looks good - thanks again!
