### ISSUE TITLE
Sencha Cmd: Remove "Generated by CoffeeScript" Lines from Built JavaScript Files

### ISSUE THREAD

**Issue by superstructor** [deftjs/DeftJS#93]
`deft.js`, `deft-debug.js` and `deft-dev.js` require `// Generated by CoffeeScript` lines to be removed during `sencha package build`.

**Comment by johnyanarella** [comment]
Honestly, it's fine with me if these end up staying in the generated output.

**Comment by johnyanarella** [comment]
In fact, after pondering it longer, I think I'd actually prefer they remain.
